# Success messages
SUCCESS_USER_REGISTERED = "User registered successfully."
SUCCESS_LOGOUT = "Token successfully blacklisted."
SUCCESS_PROJECT_CREATED = "Project created successfully."
SUCCESS_PROJECT_UPDATED = "Project updated successfully."
SUCCESS_PROJECT_DELETED = "Project deleted successfully."
SUCCESS_COMMENT_CREATED = "Comment added successfully."
SUCCESS_COMMENT_UPDATED = "Comment updated successfully."
SUCCESS_COMMENT_DELETED = "Comment deleted successfully."
SUCCESS_ROLE_ASSIGNED = "Role assigned successfully."
SUCCESS_ROLE_REMOVED = "Role removed successfully."

# Error messages
ERROR_FETCHING_PROFILE = "Failed to fetch the user profile"
ERROR_USER_REGISTRATION_FAILED = "User registration failed."
ERROR_INVALID_REFRESH_TOKEN = "Invalid refresh token."
ERROR_SOMETHING_WENT_WRONG = "Something went wrong."
ERROR_USER_ALREADY_HAS_ROLE = "This user already has a role in this project."
ERROR_UNAUTHORIZED_ROLE_ASSIGN = "Only owners can assign roles."
ERROR_PERMISSION_DENIED = "You do not have permission to perform this action."
ERROR_NOT_FOUND = "The requested resource was not found."
ERROR_INVALID_DATA = "Invalid data provided."
ERROR_FETCHING_PROJECTS = "An error occurred while fetching projects."
ERROR_CREATING_PROJECT = "Failed to create the project."
ERROR_UPDATING_PROJECT = "An error occurred while updating the project."
ERROR_DELETING_PROJECT = "An error occurred while deleting the project."
ERROR_PROJECT_NOT_FOUND = "The requested project was not found."

ERROR_ROLE_ASSIGNMENT_FAILED = "An error occurred while assigning the role."

ERROR_CREATING_COMMENT = "Failed to create the comment."
ERROR_UPDATING_COMMENT = "An error occurred while updating the comment."
ERROR_DELETING_COMMENT = "An error occurred while deleting the comment."
ERROR_COMMENT_NOT_FOUND = "The requested comment was not found."
